- hosts: all
  vars:
#galaxy_server_dir: "{{ ansible_env.HOME }}/galaxy"
    galaxy_server_dir: "/home/vagrant/galaxy"
    galaxy_config_dir: "{{ galaxy_server_dir }}/config"
    galaxy_mutable_config_dir: "{{ galaxy_config_dir }}"
    galaxy_vcs: git
    galaxy_fetch_dependencies: yes
    galaxy_fetch_eggs: yes
    galaxy_manage_static_setup: yes
    galaxy_manage_mutable_setup: no
    galaxy_manage_database: no
#    galaxy_config_dir: /opt/galaxy/config
#    galaxy_mutable_config_dir: /var/opt/galaxy/config
#    galaxy_mutable_data_dir: /var/opt/galaxy/data
#    galaxy_repo: https://bitbucket.org/galaxy/galaxy-central/
#    galaxy_repo: https://github.com/galaxyproject/galaxy
    galaxy_changeset_id: release_18.09
    galaxy_config:
      "server:main":
        "host": "0.0.0.0"
      "app:main":
        job_working_directory: "{{ galaxy_config_dir }}/job_working_directory"
        tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_shed_tool_conf_file }}"
        tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
        master_api_key: "admin"
#        tool_dependency_dir: "/deps"
        admin_users: "admin@w4m.org"
        conda_auto_init: True
        conda_auto_install: True
        dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"
  pre_tasks:
    - name: Install Debian prerequisites
      apt: pkg={{ item }} state=installed
      become: yes
      when: ansible_os_family == 'Debian'
      with_items:
        - git
        - python-virtualenv
        - m4    # Gi: I can't remember which tool need it -> TODO: build a Galaxy package
        - unzip # Gi: R need it to extract archive -> TODO: build a Galaxy package
    - name: Install RedHat prerequisites
      yum: pkg={{ item }} state=installed
      become: yes
      when: ansible_os_family == 'RedHat'
      with_items:
        - git
        - python-virtualenv
        - m4    # Gi: I can't remember which tool need it -> TODO: build a Galaxy package
        - unzip # Gi: R need it to extract archive -> TODO: build a Galaxy package
  roles:
    - role: ../roles/ansible-galaxy
      become: no 
